# Generated by Django 3.2.13 on 2022-09-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chattings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatting',
            name='abc',
        ),
    ]
